version: "3"

services:
  web:
    container_name: web
    build: ./nginx
    env_file:
      - ./.env
    network_mode: "host"
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  db:
    container_name: postgres-db
    image: postgres:15.2
    env_file:
      - ./.env
    network_mode: "host"
    volumes:
      - database-volume:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:7
    env_file:
      - ./.env
    network_mode: "host"
  # code base
  social-client:
    container_name: social-client
    build: ../vboard-social-client/
    env_file:
      - ./.env
    network_mode: "host"
    volumes:
      - ../vboard-social-client/:/app
    command: [ "npm", "run", "dev" ]
  social-server:
    container_name: social-server
    build: ../vboard-social-server/
    env_file:
      - ./.env
    network_mode: "host"
    volumes:
      - ../vboard-social-server/:/app
    command: [ "npm", "run", "dev" ]
  social-socket:
    container_name: social-socket
    build: ../vboard-social-socket/
    env_file:
      - ./.env
    network_mode: "host"
    volumes:
      - ../vboard-social-socket/:/app
    command: [ "npm", "run", "dev" ]

volumes:
  database-volume:
